# -*- coding: utf-8 -*-
"""Copy of #1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-0G-JirFcQCNaAUhhybYJICjy4_VG7R
"""

temp_celsius = 30
temp_fahrenheit = (9 / 5) * temp_celsius + 32

# Store the Fahrenheit value rounded to two decimal places
Temp_fahrenheit_rounded = round(temp_fahrenheit, 2)

# Print both temperatures in a user-friendly format
print(f"Temperature in Celsius: {temp_celsius}°C")
print("Temperature in Fahrenheit: {Temp_fahrenheit_rounded}°F")

original_price = 120
#15%off
discount = 0.15
discounted_amount =  discount * original_price
final_price= original_price-discounted_amount
print(f"original price : {original_price}")
print(f"discout_percentage: {discount *100} %")
print(f"final_price:{final_price}")

Length= 5 #m
Width = 3  # m
perimeter= 2 *(Length+Width)
Area= Length * Width
print(f"Perimeter is {perimeter}m and the Area is {Area}m^2")

number = -7

if number > 0:
    result = "Positive"
elif number < 0:
    result = "Negative"
else:
    result = "Zero"

# Print the number and the result clearly
print(f"Number: {number} and it is {result}")

total_seconds = 7384
seconds_converted_in_hrs= total_seconds/ 3600
secondsremainingwhenweconvertinhours= total_seconds % 3600
Y= secondsremainingwhenweconvertinhours % 60
print(f"{Y}")
print(f"{secondsremainingwhenweconvertinhours}")
second_converted_in_Mins = total_seconds / 60

print(f"Second:{total_seconds} is equal to {second_converted_in_Mins} minutes and also equal to{seconds_converted_in_hrs} hours")

total_seconds = 7384

# converting to  Hours
hours = total_seconds // 3600
remaining_after_hours = total_seconds % 3600

# converting to Minutes
minutes = remaining_after_hours // 60
seconds = remaining_after_hours % 60

# Output
print(f"Total Seconds: {total_seconds}")
print(f"Hours: {hours}")
print(f"Minutes: {minutes}")
print(f"Seconds: {seconds}")

test_score = (input("Enter the test score: "))


print(f"Test Score entered: {test_score}")
if 80 <= score <= 100:
    grade = "A"
elif 70 <= score <= 79:
    grade = "B"
elif 60 <= score <= 69:
    grade = "C"
elif 50 <= score <= 59:
    grade = "D"
else:
    grade = "F"

# Print the result clearly
print(f"Score: {score}")
print(f"Grade: {grade}")

print("The largest number is:", max(float(input("Enter the first number: ")), float(input("Enter the second number: ")), float(input("Enter the third number: "))))



def count_even_numbers(numbers):
    count = 0
    for num in numbers:
        if num % 2 == 0:
            count += 1
    return count

numbers = [14, 25, 36, 44, 52, 65]
print("Even numbers are:", count_even_numbers(numbers))

num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

print(f"The largest number is: {largest}")

def calculator(num1, num2, operator):
    if operator == "+":
        result = num1 + num2
    elif operator == "-":
        result = num1 - num2
    elif operator == "*":
        result = num1 * num2
    elif operator == "/":
        if num2 == 0:
            print("Error: Division by zero is not allowed.")
            return None
        result = num1 / num2
    else:
        print("Error: Invalid operator.")
        return None

    print("Result:", result)
    return result


num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operator = input("Enter an operator (+, -, *, /): ")

calculator(num1, num2, operator)